from .supervisor_prompt import SUPERVISOR_SYSTEM_PROMPT, SUPERVISOR_ROUTING_PROMPT, SUPERVISOR_ROUTE_PROMPT
from .rag_prompt import RAG_SYSTEM_PROMPT, RAG_QUERY_PROMPT, RAG_SEARCH_PROMPT
from .web_prompt import WEB_SYSTEM_PROMPT, WEB_QUERY_PROMPT
from .web_search_prompt import WEB_SEARCH_SYSTEM_PROMPT
from .report_prompt import REPORT_SYSTEM_PROMPT, REPORT_GENERATION_PROMPT

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "SUPERVISOR_ROUTING_PROMPT",
    "SUPERVISOR_ROUTE_PROMPT",
    "RAG_SYSTEM_PROMPT",
    "RAG_QUERY_PROMPT",
    "RAG_SEARCH_PROMPT",
    "WEB_SYSTEM_PROMPT",
    "WEB_QUERY_PROMPT",
    "WEB_SEARCH_SYSTEM_PROMPT",
    "REPORT_SYSTEM_PROMPT",
    "REPORT_GENERATION_PROMPT",
]
